name: Test GCP Authentication

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test-auth.yml'

env:
  WIF_PROVIDER: ${{ secrets.DEV_WIF_PROVIDER }}
  WIF_SERVICE_ACCOUNT: ${{ secrets.DEV_WIF_SERVICE_ACCOUNT }}

permissions:
  contents: read
  id-token: write

jobs:
  test-auth:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}
